### ISSUE TITLE
Pages lost

### ISSUE THREAD

**Issue by GhhG123** [tolerious/Programming_learning_resource#4]
《白帽子讲Web安全》页面缺失较多～
[白帽子讲Web安全](http://b.englishburning.com/Security/%E7%99%BD%E5%B8%BD%E5%AD%90%E8%AE%B2Web%E5%AE%89%E5%85%A8.pdf)

**Comment by tolerious** [comment]
@GhhG123   你好，感谢提醒，已上传新版。
